language: java
jdk:
  - oraclejdk8
services:
- mysql
- postgresql
before_install:
  - mysql -e "CREATE DATABASE spring_mysql;"
  - mysql -e "CREATE USER 'spring_mysql' IDENTIFIED BY 'spring_mysql'";
  - psql -c "CREATE DATABASE spring_postgres;" -U postgres
  - psql -c "CREATE USER spring_postgres WITH PASSWORD 'spring_mysql';" -U postgres
install: 
- ./mvnw install -P -use-docker-for-it -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- ./mvnw verify -P -use-docker-for-it