language: java
jdk:
- oraclejdk8
services:
- postgresql
addons:
  postgresql: "9.4"
before_install:
  - psql -c 'create database pagila;' -U postgres
install: 
  - ./mvnw -Dpostgres-db-it.port=5432 -Dbuild.datasource.username=postgres -Dbuild.datasource.password= -Dspring.datasource.username=postgres -Dspring.datasource.password= -DskipTests=true -Dmaven.javadoc.skip=true -B -V install -P -use-docker-for-it
script:
  - ./mvnw -Dpostgres-db-it.port=5432 -Dbuild.datasource.username=postgres -Dbuild.datasource.password= -Dspring.datasource.username=postgres -Dspring.datasource.password= verify -P -use-docker-for-it
